[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/payload"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/payload"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."payload"]
  timeout = 30
  memory = 1024
